### ISSUE TITLE
Normalización de respuestas a correo

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/estatutos#14]
Actualmente el sistema de respuestas a los correos de ASROB está siendo heterogéneo y errático. Yo se lo atribuyo en gran parte a que somos una asociación horizontal y distribuida gestionando un recurso centralizado, con lo cual lo hacemos de forma muy poco eficiente.

Los principales puntos a mejorar (y mis propuestas para ello) son:

* **Contestaciones homogéneas**: tener una serie de mensajes tipo que se envíen a todo el mundo que hace un determinado tipo de petición, independientemente de su género, nivel o afiliación. 
* **Roles delimitados según temática**: cada temática (nuevos miembros, impresoras 3D, IEEE, etc) es contestada por una persona que se responsabiliza de esa temática.
* **Contestaciones rápidas**: procurar que normalmente no pasen más de 48h desde que se recibe el mensaje.
* **Contestaciones institucionales**: si es una decisión a tomar, issue y votación en [actas](https://github.com/asrob-uc3m/actas). Si no, habría que idear una forma de contestar más eficiente.

¿Alguna idea o comentario?

**Comment by jgvictores** [comment]
La idea de los roles según temática suena bien, pero veo que su implementación puede fracasar debido a que en muchas ocasiones no queda clara la clasificación y los responsables se pueden desentender (salvo que les cuadre con su agenda personal).

Hemos hablado de la creación de un puesto de Responsable de respuestas a correo. Tal Responsable debería proporcionar, **evitando cualquier tipo de [discriminación](https://es.wikipedia.org/wiki/Discriminaci%C3%B3n), trato preferente o prejuiciosa**:
* **Contestaciones por plantilla**: Tener una serie de mensajes tipo por temática (nuevos miembros, impresoras 3D, IEEE, etc) que se envíen **a todo aquel** que hace un determinado tipo de petición.
* **Si se trata de una decisión a tomar**: Si se trata de una decisión a tomar, se pone issue en [actas](https://github.com/asrob-uc3m/actas) y votación siguiendo el clásico procedimiento documentado en los [estatutos de la Asociación](https://github.com/asrob-uc3m/estatutos/blob/26376c2d190eceff1090c13a1d37b02c4186b6d2/metodo_de_votacion.md).
* **Si va más allá de una plantilla o una decisión**: Esto sin duda es lo más difícil de implementar, puesto que requiere una **neutralidad e imparcialidad absoluta en cuanto al contenido de lo que se contesta**. Se seguirá además la metodología de evitar cualquier tipo de [discriminación](https://es.wikipedia.org/wiki/Discriminaci%C3%B3n), trato preferente o prejuiciosa.
* **Contestaciones rápidas**: Que no pasen más de 48h desde que se recibe el mensaje **para todo aquel** que escriba. Si se trata de tomar una decisión, se envía un mensaje comunicando que se pasará a una fase de votación interna que durará los días estipulados por los [estatutos](https://github.com/asrob-uc3m/estatutos), y se le contesta de nuevo una vez finalizada la votación.

¿Cómo lo veis?

**Comment by David-Estevez** [comment]
¿Y respecto a los mensajes que se quedan en el filtro anti-spam de Google (de los cuales el 90% no es spam)?

**Comment by jgvictores** [comment]
> ¿Y respecto a los mensajes que se quedan en el filtro anti-spam de Google (de los cuales el 90% no es spam)?

Creo que te refieres al filtro del grupo, que no se puede configurar.
La idea es que al email en sí, sí que le llegan los mensajes. Por tanto, desde el email hay que contestar siempre con copia al grupo (al cabo de un rato Google se da cuenta de que hay una realimentación cíclica y rompe un posible bucle infinito, pero eso es automático, lo importante es que todo llega a todos).

**Comment by David-Estevez** [comment]
Más bien me refería a que si este responsable también estaría a cargo de desbloquear dichos emails del filtro para que llegasen (por ejemplo, emails que no requieren respuesta).

**Comment by jgvictores** [comment]
Sí, estaría bien que alguien se encargase de esto, y tiene sentido que sea la misma persona.

**Comment by KFRodicio** [comment]
Por lo general me llegan siempre todos los correos de asrob, porque tengo la cuenta en el móvil, no me importa hacer yo esas tareas

**Comment by jgvictores** [comment]
¿Ok con poner una votación única donde simultáneamente votamos la creación del puesto (a registrar en los estatutos) + la candidatura (a documentar resultado en wiki)?

**Comment by KFRodicio** [comment]
Si, que una de las opciones sea estar en contra de que se cree el cargo, y
si votas por alguien, entonces es que estás de acuerdo con crearlo. A mi me
parece bien

El 3/12/2016 5:29 p. m., "Juan G. Victores" <notifications@github.com>
escribió:

¿Ok con poner una votación única donde simultáneamente votamos la creación
del puesto (a registrar en los estatutos) + la candidatura (a documentar
resultado en wiki)?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/asrob-uc3m/estatutos/issues/14#issuecomment-264649407>,
or mute the thread

**Comment by jgvictores** [comment]
Votación abierta hasta Dic 10 2016:

https://goo.gl/forms/dBE08xtq5N2qw7dZ2

**Comment by jgvictores** [comment]
La votación ha salido favorable: 100% a favor, 0 en contra, 0 da igual.

Actualizaré los estatutos y cerraré la issue cuando tenga un momento, ¡pero ya es oficial (de la votación: "El único candidato es KFRodicio, que asumiría el cargo con efecto inmediato en caso de aprobación.")!

**Comment by jgvictores** [comment]
Creado http://asrob.uc3m.es/index.php/Lista_de_socios#Responsable_de_respuestas_a_correo
