### ISSUE TITLE
Enfatizar el hecho que se debe ser neutral y políticamente correcto en RRSS

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/estatutos#17]
Enfatizar el hecho que se debe ser neutral y políticamente correcto en RRSS.

Cuando pueda, haré un PR y una votación para decidir si se incluye o no.

**Comment by Siotma** [comment]
Por el mismo precio, se podrían establecer unas directrices sencillas que indiquen cómo actuar en caso de que surja una polémica relacionada con las redes sociales de ASROB.

**Comment by jgvictores** [comment]
`cerrado por inactividad > 1 mes`.

**Comment by JorFru** [comment]
La idea fue captada @jgvictores gracias
