### ISSUE TITLE
Añadir una sección sobre la seguridad de la asociación.

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/estatutos#18]
A raíz de https://github.com/asrob-uc3m/actas/issues/140, me he dado cuenta de que no tenemos gestionado este tema, o eso creo, por lo que propongo añadir una sección a los estatutos sobre seguridad a nivel de Asociación, en la que gestionar y dejar por escrito los medios existentes y en poder de quién están.

Habría que hacer al menos una sección para las llaves de los armarios y otra para las llaves de las impresoras.

Propuesta:

## Seguridad de los armarios.

* El armario 1 se cierra mediante un candado. Las llaves de este candado estarán en poder de:
  * El [manojo único](https://github.com/asrob-uc3m/actas/issues/65) (:ring:), en poder del Presidente de la Asociación.
  * Los responsables de [Grupos de Trabajo Activos](https://asrob-uc3m.gitbooks.io/estatutos/content/definiciones.html), listados en la [web](http://asrob-uc3m.github.io/members.html).
  * Etc. Se admiten sugerencias.
* El armario 2 se cierra mediante una cerradura redonda y un candado. Las llaves de ambos se encuentran:
  * En el [manojo único](https://github.com/asrob-uc3m/actas/issues/65) (:ring:), en poder del Presidente de la Asociación.
  * Dentro del armario 1, en un lugar reservado para este fin.
* La vitrina se cierra mediante la misma llave redonda que el armario 2.

## Seguridad de las impresoras 3D

* Las impresoras 3D están ancladas en su posición con cadenas, cerradas con candados. Actualmente se dispone de dos cadenas y dos candados, estos últimos comparten la misma llave.
* Existen actualmente dos copias genuinas de la llave de los candados, más una copia adicional:
  * Una de las copias genuinas se encuentra en el [manojo único](https://github.com/asrob-uc3m/actas/issues/65) (:ring:), en poder del Presidente de la Asociación.
  * Otra de las copias genuinas está en poder del Responsable de Impresoras 3D.
  * La copia adicional estará en poder de un responsable de [Grupo de Trabajo Activo](https://asrob-uc3m.gitbooks.io/estatutos/content/definiciones.html) que se dedique a la investigación, y/o mantenimiento de las impresoras 3D de la Asociación. Si no existe ningún Grupo de Trabajo con estas características, esta llave pasará al manojo único.
* La custodia de cada una de las llaves es responsabilidad personal de la persona a la que estén asignadas, y se deberá comunicar de forma inmediata su pérdida o deterioro. Si se desea transferir su custodia a otra persona, se deberá aprobar mediante el método de votación vigente en la Asociación.
* Se prohíbe expresamente realizar copias de las llaves sin haber sido aprobado previamente mediante el método de votación vigente en la Asociación.

**Comment by David-Estevez** [comment]
Me mola mucho la propuesta. ¿Dejamos unos días por si alguien propone algún cambio o añadido a lo que has escrito y luego lo votamos para incluirlo?

**Comment by jgvictores** [comment]
Gracias por esta propuesta, me parece genial documentar todo esto.
La wiki no tiene info acerca de llaves, únicamente apunta a https://github.com/asrob-uc3m/actas/issues/15. Algo que aporta https://github.com/asrob-uc3m/actas/issues/15 es que cada grupo tiene 2 llaves. No estoy a favor ni en contra, pero sí está muy bien el documentar si esto son 2, o 2 pares, o qué. :-)

**Comment by jgvictores** [comment]
BTW:
- Si es específico de llaves, igual podemos llamarlo llaves. Quizás sea cosa mía que leo seguridad y pienso tb en ciberseguridad/contraseñas.
- No sé si hemos mencionado algo de la llave de la nave como tal. Supongo que deberíamos.

**Comment by Siotma** [comment]
Se podría crear un archivo .md en el repositorio (en una carpeta WIP o algo así), e ir trabajando sobre él. Para que cada uno pueda materializar las ideas que tenga y los demás vean exactamente cómo quedarían.

**Comment by Siotma** [comment]
En verdad creo que acabo de describir la utilidad exacta de un Branch :rofl:

**Comment by David-Estevez** [comment]
Sólo por ser un poco pedante:

>  Si es específico de llaves, igual podemos llamarlo llaves. Quizás sea cosa mía que leo seguridad y pienso tb en ciberseguridad/contraseñas.

Seguridad -> llaves
Ciberseguridad -> llaves virtuales (passwords) 

Así que el nombre no tiene por qué estar mal :stuck_out_tongue_winking_eye: 

Por lo demás, me mola el que estén controladas las llaves.

**Comment by JuanFdelArco** [comment]
Lo digo por aquí para que quede documentado:

- Del armario 1 tengo una llave en mi poder (que costó sus 1,5€ depositados en Piggy, así como, dato [puede considerarse donación en favor de un bien mayor]).

Lo digo para tenerlo en cuenta a la hora de tener localizadas las llaves y quién tiene alguna en su poder. En caso de escasez de llaves, la mía queda a total disposición de la asociación entendida como mente colmena (Vamos, que yo casi no la uso desde hace tiempo y si alguien la necesita yo se la cedo con gusto :D ).

**Comment by jgvictores** [comment]
Por contribuir a la documentación:
- Sigo con el juego de 3 llaves denominado manojo único (:ring:), véase foto de https://github.com/asrob-uc3m/actas/issues/65#issuecomment-285311688
- También tengo una llave del armario 1, y una llave de la nave.

**Comment by David-Estevez** [comment]
En mi caso:

* Llave de la nave (obtenida de forma ajena a ASROB)
* Llave del armario (por ser responsable de grupo activo)

**Comment by GioSunrider** [comment]
En mi caso, tengo llave de la nave, del armario 1 y de las impresoras. Todas ellas como uno de los responsables de Printer One.

**Comment by Siotma** [comment]
Yo tengo llave de:
- La nave.
- El armario 1.
- Los candados de las impresoras.

> igual podemos llamarlo llaves

Me gusta la idea de que el fichero se llame llaves.md es conciso y directo. Así no corremos el riesgo de que crezca demasiado añadiendo más cosas. Además, así es autoexplicativo. Creo que las contraseñas merecerían un (hipotético) fichero nuevo llamado passwords.md (que podría redireccionar a la wiki por ejemplo).

He creado un fichero para trabajar sobre él en https://github.com/asrob-uc3m/estatutos/blob/develop/llaves.md

**Comment by David-Estevez** [comment]
> Creo que las contraseñas merecerían un (hipotético) fichero nuevo llamado passwords.md

No sería buena idea tener las contraseñas en github, ya que es público.

>  (que podría redireccionar a la wiki por ejemplo).

Esto empieza a tener más sentido, aunque creo que con un link bastaría.

**Comment by Siotma** [comment]
Antes de que esto se muera, deberíamos hacer una votación para aprobarlo y las modificaciones y mejoras ya irán viniendo cuando hagan falta...

**Comment by JorFru** [comment]
Por anotar las cosas que no falte.

Soy el responsable de FENIX (proclamado en [ver acta](https://github.com/asrob-uc3m/FENIX/blob/master/Acta%20Reunion%2004-10-2018%20.txt)) y este grupo no tiene llave.

Procedo a sacar copia para puerta de la nave y armario.

**Comment by JorFru** [comment]
Sugiero y me propongo voluntario para crear un documento dentro de ESTATUTOS que recoja las personas que tienen llave y su posición dentro de la asociación (jefe de grupo activo, presidente, y demás gente con derecho a poseer llave y que la custodien)

**Comment by jgvictores** [comment]
Me parece bien la idea. Una cosa importante: la información de puestoResponsabilidad-nombrePersona está en la web. Enlazar correctamente esta info en lugar de duplicarla trae dos beneficios:
1) Más posibilidad de que la info sea la correcta actualizada
2) Estatutos sólo con commits de lo que son puramente estatutos (vs nombresResponsables q son intrínsecamente dinámicos)

La única modificación que exige en la web de cada Grupo Activo es ampliar Responsable a Responsable 1 y Responsable 2, lo cual está bien pq siempre se habló de 2 llaves y así está explícito.

Para más info, leer acerca de soluciones [DRY vs WET](https://en.m.wikipedia.org/wiki/Don%27t_repeat_yourself#DRY_vs_WET_solutions). :smile:

**Comment by JorFru** [comment]
Qué sugieres?
¿¿¿ Publicar en la web la información: puestoResponsabilidad-NombrePersona-LlavesQuePosee ???
¿¿¿ O simplemente puestoResponsabilidad-NombrePersona y simplemente dar por hecho que posee las llaves? ???

**Comment by jgvictores** [comment]
Tengo cierta preferencia por lo segundo:
- En web puestoReponsabilidad-nombre
- En estatutos puestoResponsabilidad-llaves

Y después abrir issues específicos cuando exista alguna incongruencia (p.ej. yo abriré una issue en actas de q debo pasarle el manojo único a @David-Estevez, citando el apartado de estatutos correspondiente).

**Comment by David-Estevez** [comment]
Acabo de crear un borrador de enmienda en una rama "enmienda-llaves" en este mismo repo: https://github.com/asrob-uc3m/estatutos/tree/enmienda-llaves

Contiene parte de lo hablado hasta ahora, y faltan cosas que todavía no se han decidido, sugiero que lo tomemos como punto de partida para resolver esta issue.

Cosas que faltan (que yo haya detectado):

* Determinar quién debería tener llaves de la nave, y cuántas
* Determinar dónde dejar constancia de quién tiene qué llave

**Comment by JorFru** [comment]
David, yo creo que:

> * Determinar quién debería tener llaves de la nave, y cuántas

Cada grupo activo puede gestionar quién es el elegido para poseer las llaves, con votación mediante como sugiere @David-Estevez . Votación interna en el grupo de trabajo ¿verdad?

A mi forma de ver, las únicas personas aptas para poseer las llaves son los responsables de grupo activo. Entonces, si alguien quiere tener llaves, debe de adquirir responsabilidades. Y si quiere llaves debe de involucrarse más en las tareas del grupo activo.
Por lo tanto, una votación para transferencia de llaves, es una tranferencia de responsabilidades de trabajo que recompensa con la posesión de las llaves.


> * Determinar dónde dejar constancia de quién tiene qué llave

Por este método que sugiero la información en web estaría en todo momento activa, porque son los responsables de grupo activo quienes poseen llaves, y estos están reflejados en la web. (Y en estatutos queda apuntado que la llave la tienen los responsables de grupo actualizados en la web)

**Comment by JorFru** [comment]
Holaaa
Esto es una prueba para comprobar que GitHub funciona y no me va a sudar de mi mensaje otra vez

**Comment by David-Estevez** [comment]
> David, yo creo que:
>
>  >    Determinar quién debería tener llaves de la nave, y cuántas
>
> Cada grupo activo puede gestionar quién es el elegido para poseer las llaves, con votación mediante como sugiere @David-Estevez . Votación interna en el grupo de trabajo ¿verdad?

Hasta ahora hemos estado hablando de llaves del armario, y hemos llegado más o menos al consenso de que debería haber 2 por grupo. Mi frase se refería a llaves de la nave, no del armario. La nave es un espacio cedido por un Departamento, que está en medio de una zona de trabajo / docencia. Pese a que siempre intentamos molestar lo menos posible al resto de personas que realizan su trabajo en este mismo espacio, cuantas más llaves más posibilidades hay de que nos llamen la atención. Recordad que estamos en ese espacio por una cesión, y que si damos mucho la lata pueden echarnos de ahí, cosa que no interesa a ninguna de las dos partes. De ahí lo de decidir cuántas deberían existir.

> A mi forma de ver, las únicas personas aptas para poseer las llaves son los jefes de grupo activo. Entonces, si alguien quiere tener llaves, debe de adquirir responsabilidades. Y si quiere llaves debe de involucrarse más en las tareas del grupo activo.
Por lo tanto, una votación para transferencia de llaves, es una tranferencia de responsabilidades de trabajo que recompensa con la posesión de las llaves.

Bajo mi punto de vista el tener llaves es una cuestión de logísitica del grupo: ¿hay alguien que siempre puede venir a las reuniones, o que llega antes que el resto? ¿Hay alguien que siempre se queda trabajando más tiempo y no quiere quedarse encerrado? Esas personas deberían tener llave. Ante todo es  autogestión de cada grupo y no creo que haya que crear la figura de un segundo responsable de grupo activo sólo para que disponga de llaves.

**Comment by GioSunrider** [comment]
Yo la verdad que pienso como @JorFru, crear un segundo responsable, darle llave y reflejarlo. Pero que así ayude a la gestión grupo, ejemplo con los doodles. Refeljar en la web quien tiene llave mediante el método de responsabilidad y apañado. También recuerdo que en el caso de Printer One Los responsables tienen llave de Nave, Armario e Impresoras. Respecto a las llaves de la nave, al final solo y como mucho 10 personas (2 responsables de grupo por grupo, responsable de impresoras y presidente con el manojo único) serian las elegidas para tener llave,  y tal y como está la asociación hoy en día ostentamos varios cargos las mismas personas luego la lista se reduce considerablemente.

**Comment by David-Estevez** [comment]
A mi me gusta pensar, aunque igual es sólo mi punto de vista, que el responsable del grupo es alguien que da soporte y una visión al grupo, no la probre personita que se come los marrones administrativos (p. ej. hacer doodles). Creo que añadiendo otro responsable se está favoreciendo el que la gente se implique menos, ya que hay alguien designado para esas tareas, en lugar de hacer piña y apechugar todos con los marrones venideros.

**Comment by JorFru** [comment]
Yo considero a ASROB una meritocracia.
Tener la llave es un honor y una motivación para cualquier participante en el grupo activo, en todo caso los doodles deberían de ser organizados por el aspirante a jefe de grupo.

> Recordad que estamos en ese espacio por una cesión, y que si damos mucho la lata pueden echarnos de ahí, cosa que no interesa a ninguna de las dos partes.

Cualquier persona que adquiera los méritos y el apoyo necesario de sus compañeros en una votación debería de ser suficientemente responsable para que esto no sea un problema, si no un ejemplo de correcta participación en la asociación.

**Comment by David-Estevez** [comment]
Creo que no te sigo. ¿Estás diciendo que crear Doodles es un mérito, o que debemos recompensar a los que tienen méritos con un trabajo repetitivo y aburrido como es hacer doodles?

Por otro lado, vuelvo a recordar la cuestión de la logística porque me parece muy importante. Aunque le diésemos llaves a los más meritosos, si estos no son los que llegan pronto, se quedan más tarde, o son más asiduos a las reuniones, seguríamos teniendo el mismo problema que motivó https://github.com/asrob-uc3m/actas/issues/171, que hay gente que realmente necesita esa(s) llave(s) porque si no no puede acceder a los recursos de la Asociación. Y si no pueden acceder a los recursos de la asociación, están en desventaja para ganar méritos, por lo que es difícil que consigan la llave (y sería la pescadilla :fish: que se muerde la cola).

PD:
> Cualquier persona que adquiera los méritos y el apoyo necesario de sus compañeros en una votación debería de ser suficientemente responsable para que esto no sea un problema, si no un ejemplo de correcta participación en la asociación.

En el país de los ciegos, el tuerto es el rey.

**Comment by JorFru** [comment]
> Creo que no te sigo. ¿Estás diciendo que crear Doodles es un mérito, o que debemos recompensar a los que tienen méritos con un trabajo repetitivo y aburrido como es hacer doodles?

Encargarse de los Doodles es un mecanismo válido como cualquier otro para ascender en la meritocracia.
El jefe de grupo tiene cosas más importantes que gestionar que un Doodle, creo.

**Comment by David-Estevez** [comment]
Si el jefe de grupo llega a jefe por méritos, y encargarse de los Doodles es un mecanismo válido como cualquier otro para ascender en la meritocracia entonces el jefe de grupo puede llegar a ser jefe de grupo a base de encargarse de Doodles. Lo cual entraría en contradicción con "El jefe de grupo tiene cosas más importantes que gestionar que un Doodle, creo".

Precisamente porque el jefe de grupo tiene cosas más importantes que gestionar un doodle es la razón por la que creo que todos dentro de un mismo grupo de trabajo deberíamos colaborar para que a todo el mundo le toque la menor parte de gestión posible, de esta forma se incrementa el cacharreo.

**Comment by jgvictores** [comment]
Respecto a terminología, [según los estatutos actuales](https://github.com/asrob-uc3m/estatutos/blob/ea879e2813dcefa7693ce3fbe3b8749f23158e25/puestos_de_responsabilidad.md#responsable-de-grupo-de-trabajo) no existen Jefes sino Responsables (se lo comenté a @JorFru y lo editó, @David-Estevez me recomendó comentarlo aquí directamente,, ¡la verdad es que se ahorra editar bastante!). Agradecería que nos ciñésemos a la nomenclatura contemplada en los estatutos, no por semántica sino por coherencia interna.

Por recordar la idea inicial de antaño (pre-estatutos :dragon:), "Responsable" viene de "Responsable de abrir puerta y armario, y colocar router". Estuvimos a punto de llamarlo "Bedel". Me parece perfecto que esto se modifique (de hecho, según estatutos actuales tb tiene función de portavoz), pero creo que modificar Responsable se merecería otra issue aparte.

Volviendo a tema llaves y documentación, sólo entrando a comentar sobre cómo se documenta la relación llaves/grupo, veo un par de alternativas que alivianan el debate "1 vs 2 responsables" y "méritos" dejándolo para otra(s) issue(s):
1) Se mantiene el status quo de la web, y en estatutos se especifica que el Responsable es la persona de contacto para averiguar quién tiene qué llave(s) que corresponden al grupo
2) La página de cada grupo dentro de la web se actualiza para documentar quién tiene llave(s) en cada momento

**Comment by David-Estevez** [comment]
La 2) no me parece mala opción.

**Comment by jgvictores** [comment]
Por mover esto, abierta votación hasta 7/nov/2018 a las 16:20 horario Madrid:
https://goo.gl/forms/UN7Ttlu0iGdxCP6l2

**Comment by jgvictores** [comment]
Consulta cerrada con 3 a favor, 1 ni fu ni fa, 0 en contra.

![screenshot from 2018-11-12 11-02-23](https://user-images.githubusercontent.com/4448588/48343553-91182280-e66a-11e8-92f8-c9083f5df896.png)

**Comment by jgvictores** [comment]
Merged at 4fc20c22f2da512036d724a37c2b3327f09fd759.
