### ISSUE TITLE
Los correos que llegan a nuestro email no se están contestando

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/estatutos#19]
Ahora mismo hay cinco personas que han contactado con nosotros para intentar unirse a nuestra asociación y no pueden.
Es el momento más importante del curso para la captación, no podemos dejarlos pasar.

**Comment by David-Estevez** [comment]
@KFRodicio me comentó que les mandaría un mensaje genérico dirigiéndoles al Telegram.

PD: ¿esto no iría en actas?

**Comment by jgvictores** [comment]
This issue was moved to asrob-uc3m/actas#163
