### ISSUE TITLE
Incluir en los estatutos los cambios en la gestión de Telegram: grupo horizontal

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/estatutos#21]
En la issue https://github.com/asrob-uc3m/actas/issues/174 se han decidido cosas.

Procedo a redactar un borrador de las reglas que van a quedar escritas en los estatutos.

Me he fijado que la sección https://github.com/asrob-uc3m/estatutos/blob/master/llaves.md tiene una forma que puede encajar para esta nueva sección.

Creo que lo mejor sería abrir una sección llamada admin_Telegram.md
¿Opiniones?

**Comment by JorFru** [comment]
Este es el borrador.
Sugerencias?

https://github.com/JorFru/estatutos/blob/master/admin_telegram.md

**Comment by David-Estevez** [comment]
A mi me mola, incluye todo lo que había que documentar :+1: 

Quizá cambiaría el título de "admin_telegram" a "Administración de Telegram" para que se integre bien en el gitbook de los Estatutos. Siguiendo en la misma línea, y tras https://github.com/asrob-uc3m/actas/issues/148, no sé si habría que añadir algo más para que esa página apareciese en el indice del gitbook. ¿tocar SUMMARY.md quizá?

**Comment by jgvictores** [comment]
Sí, meterlo como un punto más de `SUMMARY.md` es necesario para que se genere como página del gitbook. : )

**Comment by JorFru** [comment]
> Quizá cambiaría el título de "admin_telegram" a "Administración de Telegram" para que se integre bien en el gitbook de los Estatutos.

Yo vi que el resto de nombres eran minimalistas y sin espacios, a si que seguí la estética de los otros archivos que forman las secciones de los estatutos.

He investigado un poco sobre lo de que se publique en gitbooks, creo que lo conseguiré.

**Comment by David-Estevez** [comment]
Decía el título, no el nombre de archivo. El nombre de archivo está bien.

**Comment by JorFru** [comment]
Muy bien, pues si esto os parece bien, organizo votación para que se mergee con una pull request.

**Comment by JorFru** [comment]
Aquí la votación.
https://docs.google.com/forms/d/e/1FAIpQLSfmchTzLTtRVPYfI9w6_d90hTROu2DgN46GwQL33lyP__Yebg/viewform?usp=sf_link

Si sale a favor mergearé y haré lo del SUMMARY.MD y tal.

**Comment by JorFru** [comment]
![image](https://user-images.githubusercontent.com/11017088/52407011-686bc180-2acf-11e9-95d0-0300d2a1810d.png)
Procedemos
