### ISSUE TITLE
Nuevo horario Robofactory

### ISSUE THREAD

**Issue by madelgj** [asrob-uc3m/estatutos#23]
Teniendo en cuenta la modificación de horario de Robofactory y que ahora hay dos horarios fijos (lunes por la tarde y jueves por la mañana) y que el actual responsable @David-Estevez solo puede asistir a uno de ellos, creo conveniente el tener otra llave para poder abrir la nave los jueves a las personas que asistiremos ese día. Y, tras lo q se dijo en #18 de haber dos llaves por grupo activo, me propongo como responsable de esas reuniones (quiero una llave) 🦄 🔑 🤖 🎋 🚀

**Comment by jgvictores** [comment]
¿Es posible que esto no afecte a los Estatutos como tal, y sea un duplicado de https://github.com/asrob-uc3m/actas/issues/171 ?

**Comment by GioSunrider** [comment]
Sin duda es duplicado xD Pero ahora es urgente jajajajaj

**Comment by jgvictores** [comment]
He subido la prioridad a https://github.com/asrob-uc3m/actas/issues/171
¿Podemos cerrar esto como duplicado?

**Comment by GioSunrider** [comment]
Yo creo que si, igual hay que cambiar el nombre de la otra y solucionarla.

**Comment by jgvictores** [comment]
Totalmente de acuerdo!
