### ISSUE TITLE
Renovación cargo responsable de correos

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/estatutos#24]
Se ha presentado @dag00dag33 como candidato para esta tarea.
El responsable actual es @KFRodicio . Si lo desseas puedes demostrar interés para renovar el cargo en la próxima votación.

https://github.com/asrob-uc3m/actas/issues/163

**Comment by David-Estevez** [comment]
¿Y la votación... ?

**Comment by JorFru** [comment]
La votación se hará por los medios habituales, Google Forms.
Se consideró que una votación con los allí presentes no iba a representar
la totalidad de la asociación. Aunque éramos bastantes la verdad.

**Comment by JorFru** [comment]
https://forms.gle/geNFhBtiGTme4ee2A

**Comment by JorFru** [comment]
Después de los 7 días de rigor, el resultado de la votación es el siguiente
![imagen](https://user-images.githubusercontent.com/11017088/65188589-0fa1d580-da6f-11e9-8cb2-8dc2a3ee356e.png)

Por lo tanto, ¡tenemos nuevo Responsable de Correos!
Enhorabuena @DAG00DAG33

**Comment by jgvictores** [comment]
Si todo cerrado, podéis porfa actualizar https://github.com/asrob-uc3m/asrob-uc3m.github.io/blob/master/_config.yml#L86-L88 ([permalink](https://github.com/asrob-uc3m/asrob-uc3m.github.io/blob/fe9e3ab879197f2b225c69e39a4c55a93974b92e/_config.yml#L86-L88))?

Thanks!

**Comment by JorFru** [comment]
Gracias por el recordatorio @jgvictores 
Ya está hecho

**Comment by jgvictores** [comment]
Apunto a commit: https://github.com/asrob-uc3m/asrob-uc3m.github.io/commit/4c62998c4c151a46823c368c0ff2fba3c181d17b
