### ISSUE TITLE
Propuesta de una nueva forma de votación para decisiones putuales y rápidas

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/estatutos#25]
El método de votación actual es completo y perfectamente válido, pero requiere bastante tiempo para cumplimentarse.
Detalles del método actual: https://github.com/asrob-uc3m/estatutos/blob/master/metodo_de_votacion.md

Propongo las votaciones de Telegram, que pueden hacerse en el grupo ASROB Horizontal, o en el grupo de Rama de ASROB (si sólo depende de la gente de esa Rama).

Sugiero introducir esta frase en el documento antes citado.

```
Como método de votación alternativo compatible con las tareas o decisiones puntuales de la asociación se puede realizar una votación en nuestros grupos de Telegram.
En el grupo de Telegram ASROB: Organización Horizontal (como Valve) para las decisiones que incumben a todos los asociados.
En el grupo de Telegram de cada Rama para decisiones que sólo incumben a los integrantes de ese grupo.
```

Queda abierto el periodo para complementar esta idea.
Próximamente una votación para incorporarla a los estatutos.

**Comment by David-Estevez** [comment]
Me mola la idea de tener un método alternativo para proponer votaciones más rápido que crear un form, ya que muchas veces la burocracia que tenemos montada nos hace ser más lentos. De hecho ya se empezó a trabajar en esta dirección en #15.

No obstante, yo le veo ~~dos~~ una desventaja~~s~~ al método propuesto:

~~1. El método de votación no es anónimo, lo cual puede condicionar la votación.~~
2. En el grupo de ASROB hay gente que ni es miembro activo, ni es siquiera miembro de la asociación. Normalmente les dejamos estar porque son voyeurs, sólo miran y no molestan, pero en este caso podrían también participar en las votaciones (lo cual va contra los estatutos actuales).

Editado para tener en cuenta de que sí que se pueden hacer anónimas.

**Comment by JorFru** [comment]
Sí se pueden organizar votaciones anónimas dentro de un grupo de Telegram

**Comment by jgvictores** [comment]
> Detalles del método actual: https://github.com/asrob-uc3m/estatutos/blob/master/metodo_de_votacion.md

Apunto al commit `at time of writing`: https://github.com/asrob-uc3m/estatutos/blob/b681f4e7ce8bdcfee5069526f4d8fa4927efcd45/metodo_de_votacion.md

**Comment by jgvictores** [comment]
@JorFru ¿La propuesta mantiene el plazo de 24 horas mínimo?

**Comment by JorFru** [comment]
Sí, 24h

**Comment by David-Estevez** [comment]
¿Cualquiera puede crear las votaciones?

**Comment by JorFru** [comment]
Cualquiera puede crear las votaciones.

**Comment by GioSunrider** [comment]
Yo propongo que mi uno la votación sea obligado anclarla, que hay veces que se pierden los mensajes.

**Comment by David-Estevez** [comment]
> Cualquiera puede crear las votaciones.

Entonces yo pondría alguna norma para que no se convierta en un cachondeo (todo el mundo troleando creando votaciones a la vez).

> Yo propongo que mi uno la votación sea obligado anclarla, que hay veces que se pierden los mensajes.

Yo propongo que mi uno la votación sea obligado ponerle el hastag #votacion

**Comment by GioSunrider** [comment]
Joder.... Perdón por el corrector 🤣 "que los admin". Pero también veo lo de la almohadilla.

**Comment by JorFru** [comment]
Texto nuevo con las modificaciones introducidas.

Como método de votación alternativo compatible con las tareas o decisiones puntuales de la asociación se puede realizar una votación en nuestros grupos de Telegram.
- En el grupo de Telegram ASROB: Organización Horizontal (como Valve) para las decisiones que incumben a todos los asociados.
- En el grupo de Telegram de cada Rama para decisiones que sólo incumben a los integrantes de ese grupo.

Cualquier usuario de ASROB puede crear votaciones

Las votaciones serán anónimas

La votación deberá estar un mínimo de 24h publicada y accesible, pineada en el grupo correspondiente, y debe contener el hashtag "#votación" (con tilde).

Máximo una votación en curso en cada grupo.

**Comment by JorFru** [comment]
Se está votando
https://forms.gle/E6AK7TWTjpv9QKYs6

**Comment by JorFru** [comment]
![447908013_217864](https://user-images.githubusercontent.com/11017088/71038737-ccfda100-2122-11ea-8ef1-e300891fd2e8.jpg)
Se ha votado

**Comment by JorFru** [comment]
Resultado positivo de la votación.

Asciendo la PR

**Comment by jgvictores** [comment]
Método actual: https://github.com/asrob-uc3m/estatutos/blob/49308cc8f5df707a746c789d95b59c56d85b22ff/metodo_de_votacion.md
