### ISSUE TITLE
Contenido de los estatutos

### ISSUE THREAD

**Issue by KFRodicio** [asrob-uc3m/estatutos#3]
Hay actualmente cosas que aparecen en los estatutos que no deberían salir. Los estatutos al fin y al cabo son el conjunto de normas que definen el funcionamiento de la asociación de aquí hasta que se refunde asrob. Por ejemplo, que la junta la formen el presidente, secretario, tesorero y vocales es un estatuto, pero las personas que ocupan el cargo no lo son. Otra cosa, no empezar cada frase con se propone. Si es una propuesta, todavía no es un estatuto, cuando esa propuesta se aprueba deja de ser propuesta y pasa a ser estatuto.
## Puntos que quitaría de ese fichero:

-**Junta actual**: yo diría que esto no es una norma de la asociación, esas personas no ocupan el puesto porque lo dicen los estatutos
-**Inventario**: quitar lo de que se va a hacer una reunión, el resto está bien
-**Patrocinios robokode 2015**: Tarea pendiente, no estatuto
-**Robots móviles**: más de lo mismo
-**Wiki**: está bien, pero poner mas una estructura que tendrá que decir que se va a crear tal cosa. Es decir, que diga algo como: la wiki contará con estas secciones, estos son los requisitos para ser usuario y tal. 
-**Web**: tal y como está es una tarea pendiente, asi que no es estatuto
-**IEEE student branch, Robokode 2016, Contactos externos y Otras ideas**: lo mismo que antes, son ideas de futuro o cosas que se quieren hacer, no normativa de la asociación

Todo lo que se quite de los estatutos, si se quiere dejar documentado lo que habría que acer es crear otro documento que sea "Acta reunión 24F". Uno de los puntos sería redacción de los nuevos estatutos y luego se pondrían todas las cosas que se quitarían de los estatutos

**Comment by David-Estevez** [comment]
La intención de la sección "Lineas de actuación" era la de servir como acta de reunión. Al no tener otro lugar donde ponerla, me pareció lógico ponerla en estatutos de forma temporal.

Propongo la creación de otro GitBook llamado "actas" para compilar las actas de las distintas reuniones, incluyendo las del 24F.

**Comment by David-Estevez** [comment]
He creado un nuevo [GitBook](https://www.gitbook.com/book/asrob-uc3m/actas/welcome) dedicado exclusivamente a actas de reunión. El resto del contenido que no procede se migrará paulatinamente.

**Comment by David-Estevez** [comment]
Se han creado issues correspondientes a las propuestas de la última reunión. Como tiene que ver con reuniones, los he creado en el [repo de las actas](https://github.com/asrob-uc3m/actas/milestones/Propuestas%20de%20la%20Reuni%C3%B3n%2024/02/16)

**Comment by David-Estevez** [comment]
Creo que ya no queda nada que no deba estar. De todas formas, échale un ojo @KFRodicio y reabrimos el issue si hay algo que no debería.
