### ISSUE TITLE
Adopción de un método de votación abierto y distribuido

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/estatutos#4]
Propongo que adoptemos un sistema de votación abierto y distribuido.

Ejemplos:
- [Liquid Democracy (Wikipedia)](https://en.wikipedia.org/wiki/Delegative_democracy)
- [Liquid Democracy e.V. (Berlin)](https://liqd.net/)
- [Liquid Feedback (software)](http://liquidfeedback.org/)

**Comment by jgvictores** [comment]
Propongo la utilización de Google forms. Parece la mejor solución. Como única pega está que para utlizar todas sus capacidades, hace falta algún correo acabado en uc3m.es (p.ej. alumnos.uc3m.es).

**Comment by David-Estevez** [comment]
+1!

**Comment by rodriwp** [comment]
+1

**Comment by JuanFdelArco** [comment]
+1

**Comment by RobertoHE** [comment]
+1

**Comment by jorgercobo** [comment]
+1

**Comment by KFRodicio** [comment]
+1

**Comment by David-Estevez** [comment]
@jgvictores Los de Github han implementado los +1 (likes, dislikes) de forma nativa!

**Comment by jgvictores** [comment]
Voy a cerrar esta issue en vistas a todos los +1 y la utilización que ha tenido Google Forms en https://github.com/asrob-uc3m/estatutos/issues/5.
