### ISSUE TITLE
Utilización de redes sociales y/o listas de correo

### ISSUE THREAD

**Issue by KFRodicio** [asrob-uc3m/estatutos#5]
En esta issue se irán enlazando las consultas para enmiendas respecto a redes sociales y/o listas de correo de asrob, en formato Google forms (si @jgvictores lo hizo bien, sólo se puede votar siendo parte de uc3m.es, sea alumno o profesor, y no se puede ver quién votó qué, pero sí la estadística final) para validar #4.

---
#### Texto original de la issue:

En lo que respecta a las redes sociales de ASROB, creo que se debería introducir esta propuesta (si no está ya):

Si se quieren usar las redes sociales de asrob para dar difusión/publicitar un proyecto/taller/charla que esté relacionado con una empresa (que el miembro de asrob o persona responsable  del proyecto lo haya realizado dentro de dicha empresa, por ejemplo), tienen que darse dos condiciones:

El taller/charla tiene que ser sin ánimo de lucro.

El proyecto que se desarrolle en el taller/charla, o al que se le quiera dar difusión, tiene que ser totalmente libre, entendiendo por esto, que no es necesario comprar material específico de dicha empresa o pagar nada a dicha empresa (como software necesario, por ejemplo), además de que el código y los diseños de las piezas que sean necesarias sean libres, en la medida de lo posible (independientemente de que la empresa además decida comercializar el kit o el proyecto por otra parte).

**Comment by jgvictores** [comment]
Empecemos por los siguientes puntos:
- Consulta de @KFRodicio en cuanto a difusión/publicitar un proyecto/taller/charla que esté relacionado con una empresa: http://goo.gl/forms/nf35Wm8UzU
- Consulta respecto a publicar ofertas de empleo en la [lista email](https://groups.google.com/forum/#!forum/miembros-activos-asrob) (miembros activos): http://goo.gl/forms/YpKUFR3peI

Esperamos sus respuestas! **Consultas abiertas hasta Mayo 3 a las 23:59**

**Comment by David-Estevez** [comment]
Para la próxima encuesta igual deberíamos añadir también un "Me da igual"

**Comment by jgvictores** [comment]
@David-Estevez Me parece bien lo de añadir también un "Me da igual".

**Comment by jgvictores** [comment]
Cerrando consultas:
- Consulta de @KFRodicio en cuanto a difusión/publicitar un proyecto/taller/charla que esté relacionado con una empresa: http://goo.gl/forms/nf35Wm8UzU -> 3 a favor, 0 en contra. -> Favorable.
- Consulta respecto a publicar ofertas de empleo en la [lista email](https://groups.google.com/forum/#!forum/miembros-activos-asrob) (miembros activos): http://goo.gl/forms/YpKUFR3peI -> 2 a favor, 0 en contra. -> Favorable.

Como se habló en https://github.com/asrob-uc3m/actas/issues/13, se procede al cierre de la issue (nuevas issues para nuevas enmiendas).

**Comment by jgvictores** [comment]
Actializado en https://github.com/asrob-uc3m/estatutos y por tanto en https://asrob-uc3m.gitbooks.io/estatutos/content/imagen_de_la_asociacion.html.
