### ISSUE TITLE
Mayor especificación en la Definición de Grupo de Trabajo Activo

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/estatutos#6]
En esta enmienda se manifiesta la petición popular de especificar más en la **Definición de Grupo de Trabajo Activo** en los siguientes aspectos:
1. Que el término _asiduamente_ de la  se refiere a _de forma presencial no remota, mínimo una vez por semana_.
2. El proyecto que se desarrolle en las reuniones/talleres/charlas, tiene que ser sin ánimo de lucro y totalmente libre, entendiendo por esto, que no es necesario comprar material específico de empresa o pagar nada a una empresa en particular (como software necesario, por ejemplo), además de que el código y los diseños de las piezas que sean necesarias sean libres, en la medida de lo posible (independientemente de que una empresa además decida comercializar el kit o el proyecto por otra parte).

Os dejo el link: http://goo.gl/forms/ad6mBIlPtT

**Comment by David-Estevez** [comment]
Deadline?

**Comment by jgvictores** [comment]
Perdón, estaba en el form pero no aquí: **Consulta abierta hasta Mayo 11 de 2016 a las 23:59**

Son 7 días naturales, como en https://asrob-uc3m.gitbooks.io/estatutos/content/metodo_de_votacion.html

Os dejo el link de nuevo: http://goo.gl/forms/ad6mBIlPtT
