### ISSUE TITLE
Participación en RoboCity16

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/estatutos#8]
Hola a todos!

Nos han invitado a participar en el [RoboCity16](http://www.robocity2030.org/events/event/evento-esp-2-2/). La forma de participación será un stand en el que podremos enseñar nuestros proyectos a los asistentes. Abro esta consulta para decidir de forma abierta y democrática:
1. Asistencia al evento. Si hay gente disponible e interesada en asistir, que vote a favor de este punto.
2. Difusión en las redes sociales. Si estamos de acuerdo en publicitar el evento por las redes sociales.

El form para realizar la votación es [**éste**](http://goo.gl/forms/1V5UewoDzDuYrHK43). Como es habitual, sólo se puede votar desde una cuenta UC3M siendo miembro activo de la asociación. La votación concluye el **día 19 a las 23:59h**, para poder comunicar la decisión a la organización del evento.

**Comment by jgvictores** [comment]
Me comunican que en principio el stand será de aproximadamente 3m x 3m.
En cuanto al transporte, lo ideal es que se lleve lo que queramos llevar en el mismo transporte que lleve lo del Robotics.

**Comment by JavierIH** [comment]
Saludos, a mí me gustaría ir y llevarme algunos bichos, pero como comenté las fechas se me solapan con el Euskobot. El 27 fijo que no puedo, pero el 26 quizás puedo, no estoy seguro (y probablemente no lo estaré hasta el día antes :cold_sweat: )

**Comment by David-Estevez** [comment]
Yo me puedo llevar mi serpiente :snake:, y los de Robot Devastation nos podemos llevar nuestros trastos y el ECRO.

**Comment by KFRodicio** [comment]
Dado que vamos a acudir, dejo por aquí un enlace a una hoja de doodle para que cada uno marque que día le viene mejor ir. En principio, como no tengo ni idea de los horarios, están puestos días completos, si hay que partirlo en mañana y tarde se puede discutir mas tarde.

http://doodle.com/poll/xhafqepxpf58u4hc

**Comment by jgvictores** [comment]
Os comento logística: La idea es empezar a cargar furgo Robotics desde mañana miércoles las 10:30, y estar descargando furgo a las 16:00 en el lugar.
@KFRodicio ¿Puedes editar el doodle para mañana miércoles tb, e incorporar algo más de granularidad (mañana/tarde si no es directamente por franjas horarias)?

**Comment by jgvictores** [comment]
Edit: _La idea_ es que el miércoles a las 16:00 ya estén los stands montados.

**Comment by KFRodicio** [comment]
Encuesta modificada. Para mañana miercoles, las opciones son mañana y tarde (supongo que por los horarios que da juan, mañana sería cargar y tarde descargar y montar el stand). Para el jueves y el viernes son los horarios de la conferencia, desde que empieza hasta la hora de comer y desde la hora de comer hasta que acaba

**Comment by jgvictores** [comment]
@KFRodicio Thanks! Yo tb estaré entre robotics y asrob, no pasa nada.

Os repito el link del doodle para que os apuntéis, porfa! http://doodle.com/poll/xhafqepxpf58u4hc

**Comment by jgvictores** [comment]
No sé si va aquí, pero puede ser más cómodo que utilizar el [inventario](http://asrob.uc3m.es/partkeepr-0.79/web/). Lista de objetos a llevar y/o llevados a RoboCity:
- [ ] LEDs: ?
- [x] Roll-up ASROB: @smcdiaz
- [x] Carteles nuevos varios: @David-Estevez 
- [x] Router: @David-Estevez 
- [x] Serpiente: @David-Estevez 
- [x] Robotera (ahora incluye Turret, RD2 y Piggy): @David-Estevez 
- [x] ECRO: @jgvictores
- [x] MegaKame: @jgvictores 
- [x] Gamepad de MegaKame: @jgvictores 
- [x] Raider: @JavierIH
- [x] Gamepad de Raider: @JavierIH
- [x] Kame (minikame): @JavierIH
- [x] MicroRaider: @JavierIH
- [x] Cargador LiPo (pegatina raider): @JavierIH

Edit as you like! :smiley: 
(editado por @JavierIH)

**Comment by David-Estevez** [comment]
Done!
