### ISSUE TITLE
Añadir repo para las impresoras

### ISSUE THREAD

**Issue by kleiren** [asrob-uc3m/estatutos#9]
Se podría añadir un repo para las impresoras, para permitir generar issues sobre su estado y para subir archivos relacionados (como las configuraciones de cada una)

**Comment by David-Estevez** [comment]
Creado [aquí](https://github.com/asrob-uc3m/impresoras-asrob).

También tenemos [este](https://github.com/asrob-uc3m/impresoras-user-manual-i3) y [este](https://github.com/asrob-uc3m/impresoras-maintenance-manual-i3) para documentación/manuales.
